[add][TC-COS] add TC-COS sdk v5 support
7sDream/rikka pull request #13
Opened 2019-03-07 16:24 UTC by ilumer

- 添加对腾讯云 cos v5的支持
- 添加env `RIKKA_TENCENT_REGION` 来保证 cos v5 的使用
- 添加参数 `bVersion` 来区分 v5 和 v4 的使用

2019-03-07 16:28 UTC, 7sDream commented
👍 明天晚上 Review 一下

Ref to the Issue: #12

2019-03-08 12:07 UTC, 7sDream requested changes
几个小问题可以看着改改，其它的都 OK～

2019-03-08 12:07 UTC, 7sDream commented on plugins/tencent/cos/cosargs.go
> +var ArgCosVersion = flag.String("bVersion", "", "Tencent cos sdk version")
```suggestion
var ArgCosVersion = flag.String("tccosVer", "v4", "Tencent cos sdk version, v4(default) or v5")
```

为了保持兼容性，这里需要一个默认值。另外参数的说明文档也需要明确一些。

啊我想起来了，其他参数里的 b 的意思是 bucket，这里用 bVersion 不是特别合适，换成 `tccosVersion` 之类的吧……果然还是有点长？那  `tccosVer` 好了。

2019-03-08 12:07 UTC, 7sDream commented on plugins/tencent/cos/cosargs.go
> +	if value == "" {
有默认值了，这里就可以删掉了。

2019-03-08 12:07 UTC, 7sDream commented on plugins/tencent/cos/cosargs.go
> +	return *ArgCosVersion
```suggestion
	return value
```

2019-03-08 12:07 UTC, 7sDream commented on plugins/tencent/cos/client.go
> +type GenericCosClient interface {
这个 Interface 应该也没有必要 Public?

2019-03-08 16:12 UTC, 7sDream approved these changes

2019-03-08 16:14 UTC, ilumer commented
- 修改 `code review` 中的问题
- 更新 `cos` 的readme

2019-03-08 16:15 UTC, merged